# (c) https://github.com/MontiCore/monticore

image: maven:3.5.4-jdk-11

stages:
  - build
  - check

before_script:
  - chmod +x gradlew
  - chmod +x check/downloadlinkchecker.sh
  - chmod +x check/mdlinkcheck.sh
  - export GRADLE_USER_HOME=`pwd`/.gradle


build:
  stage: build
  script:
    - "./gradlew build $GRADLE_OPT $ARGS1"
  artifacts:
    paths:
      - "target/"
      - ".gradle/"
    expire_in: 1 week

checkMDLinks:
  stage: check
  dependencies:
    - build
  script:
    - "./check/downloadlinkchecker.sh $secibuildtoken"
    - "url=https://git.rwth-aachen.de/monticore/languages/xml/-/blob/develop/src/main/grammars/de/monticore/lang/xml.md"
    - "./check/mdlinkcheck.sh -url $url -t $secibuildtoken -p"
  only:
    - dev
