// (c) https://github.com/MontiCore/monticore

/* ============================================================ */
/* ========================= Plugins ========================== */
/* ============================================================ */

plugins {
    id "java"
    id "de.monticore.generator" version "$mc_version"
    id "maven-publish"
    id "com.gradleup.shadow" version "$shadow_plugin_version"
}

/* ============================================================ */
/* ========================= Project ========================== */
/* ============================================================ */

group = "de.monticore.lang"
description = "XML"

/* ============================================================ */
/* ======================= Configuration ====================== */
/* ============================================================ */

layout.buildDirectory = layout.projectDirectory.dir("target")

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}

/* ============================================================ */
/* ======================= Dependencies ======================= */
/* ============================================================ */

repositories {
    if(("true").equals(getProperty('useLocalRepo'))){
        mavenLocal()
    }
    mavenCentral()
    maven {
        credentials.username = mavenUser
        credentials.password = mavenPassword
        url = repo
    }
}

dependencies {
    grammar "de.monticore:monticore-grammar:$mc_version"
    implementation "de.se_rwth.commons:se-commons-logging:$se_commons_version"
    implementation "org.apache.commons:commons-lang3:$commons_lang_version"
    implementation "org.assertj:assertj-core:$assertj_version"
    implementation "commons-cli:commons-cli:$commons_cli_version"
    implementation "com.google.code.findbugs:jsr305:$findbugs_version"

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"

    testImplementation "ch.qos.logback:logback-classic:$logback_version"
}

/* ============================================================ */
/* ========================== Tasks =========================== */
/* ============================================================ */


tasks.withType(Copy).configureEach { duplicatesStrategy =  DuplicatesStrategy.EXCLUDE }

tasks.withType(JavaCompile).configureEach {
  options.encoding = "UTF-8"
  options.deprecation = false
  options.warnings = false
}

// build sources jar in addition
tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allJava
    archiveClassifier = "sources"
}


// build javadoc jar in addition
tasks.register('javadocJar', Jar) {
    from javadoc
    archiveClassifier = "javadoc"
}

// generated java doc contains errors, disable for now
javadoc.failOnError = false

// all in one tool-jar
shadowJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes "Main-Class": "de.monticore.lang.xmllight.XMLLightTool"
    }
    archiveFileName = "MCXML.jar"
    archiveClassifier = "mc-tool"
}
jar.dependsOn shadowJar


/* ============================================================ */
/* ======================= Publishing ========================= */
/* ============================================================ */

publishing {
    // configure what artifacts to publish
    publications {
        mavenJava(MavenPublication) {
            artifactId = "$project.name"
            from components.java
            artifact sourcesJar
            artifact javadocJar
        }
    }
    repositories.maven {
        credentials.username = mavenUser
        credentials.password = mavenPassword
        def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
        def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
        url = version.endsWith("SNAPSHOT") ? snapshotsRepoUrl : releasesRepoUrl
    }
}

