mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
org.gradle.vfs.watch=true

#set true or use \u2013PuseLocalRepo=true to use local maven repo
useLocalRepo=false
mc_version=7.8.0
se_commons_version=7.8.0
shadow_plugin_version=7.1.2
version=7.8.0
