mavenUser=${username}
mavenPassword=${password}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
org.gradle.vfs.watch=true

#set true or use \u2013PuseLocalRepo=true to use local maven repo
useLocalRepo=false

version=7.9.0
mc_version=7.9.0

se_commons_version=7.9.0
shadow_plugin_version=8.3.9
findbugs_version=3.0.0
assertj_version=3.7.0
commons_cli_version=1.11.0
logback_version=1.1.2
commons_lang_version=3.20.0
junit_version=6.0.3
